title: Petar N. Petrov
logo: /images/headshot.png
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-last-modified-at
last-modified-at:
    date-format: '%d-%b-%Y'
